media:
  input: images
  output: /images
  path: images
  categories: [image]
content:
  - name: pages
    label: Pages
    path: pages
    type: collection
    subfolders: false
    view:
      fields: [permalink, title, metaTitle]
      primary: title
      sort: [nav_order, title]
    fields:
      - { name: title, type: string, label: Title }
      - { name: metaTitle, type: string, label: Meta Title }
      - { name: nav_order, type: number, label: Navigation Order }
      - { name: permalink, type: string, label: Permalink }
      - { name: layout, type: string, label: Layout }
      - { name: body, label: Body, type: code, options: { language: markdown } }

  - name: products
    label: Places
    path: products
    type: collection
    subfolders: false
    filename: "{primary}.md"
    view:
      fields: [title, categories, omni, restaurant, shop, delivery]
      primary: title
      sort: [title]
    fields:
      - { name: title, type: string, label: Name, required: true }
      - { name: name, type: string, label: Name (Display) }
      - { name: last_modified_at, type: date, label: Last Modified }

      # Location fields
      - { name: address, type: string, label: Address }
      - { name: postcode, type: string, label: Postcode }
      - { name: google, type: string, label: Google Maps URL }

      # Contact fields
      - { name: phone, type: string, label: Phone }
      - { name: email, type: string, label: Email }
      - { name: web, type: string, label: Website }

      # Social media fields
      - { name: facebook, type: string, label: Facebook }
      - { name: twitter, type: string, label: Twitter }
      - { name: instagram, type: string, label: Instagram }
      - { name: tripadvisor, type: string, label: TripAdvisor }

      # Business type fields
      - { name: omni, type: boolean, label: Serves Non-Vegan Food Too }
      - { name: shop, type: boolean, label: Shop }
      - { name: restaurant, type: boolean, label: Restaurant }
      - { name: delivery, type: boolean, label: Delivery Available }
      - { name: is_chain, type: boolean, label: Is Chain }

      # Category reference
      - name: categories
        label: Categories
        type: reference
        options:
          collection: categories
          multiple: true
          search: "title"
          value: "{primary}"
          label: "{title}"

      - name: times
        label: Opening Times
        type: string
        list: true

      - { name: votes, type: number, label: Votes }

      - name: reviews
        label: Reviews
        type: object
        list: true
        fields:
          - { name: text, type: text, label: Review Text, required: true }
          - { name: date, type: date, label: Date, required: true }
          - { name: url, type: string, label: URL (Instagram/Facebook) }

      - { name: body, label: Description, type: code, options: { language: markdown } }

  - name: categories
    label: Categories
    path: categories
    type: collection
    subfolders: false
    filename: "{primary}.md"
    view:
      fields: [title, subtitle, featured]
      primary: title
      sort: [title]
    fields:
      - { name: title, type: string, label: Title }
      - { name: subtitle, type: string, label: Subtitle }
      - { name: featured, type: boolean, label: Featured }
      - { name: show, type: string, label: Show Tag }
      - { name: chain_intro, type: string, label: Chain Introduction }
      - { name: non_chain_intro, type: string, label: Non-Chain Introduction }
      - { name: last_modified_at, type: date, label: Last Modified }
      - { name: body, label: Description, type: code, options: { language: markdown } }

  - name: site_config
    label: Site Configuration
    path: _data
    type: file
    file: site.json
    fields:
      - { name: name, type: string, label: Site Name }
      - { name: description, type: string, label: Site Description }
      - { name: url, type: string, label: Site URL }
      - name: socials
        label: Social Media
        type: object
        fields:
          - { name: facebook, type: string, label: Facebook }
          - { name: instagram, type: string, label: Instagram }
          - { name: rss, type: string, label: RSS Feed }

  - name: meta_config
    label: Site Metadata
    path: _data
    type: file
    file: meta.json
    fields:
      - { name: language, type: string, label: Language Code }
      - { name: legalName, type: string, label: Legal Name }
      - { name: foundingDate, type: number, label: Founding Year }
      - { name: founder, type: string, label: Founder }
      - { name: description, type: text, label: Description }
